### ISSUE TITLE
Uncaught TypeError: Invalid Point: (NaN, 0)

### ISSUE THREAD

**Issue by rodrigoAbril** [73CN0109y-Packages/folded-code-preview#3]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0-beta2 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.5
**Thrown From**: [folded-code-preview](https://github.com/73CN0109y-Packages/folded-code-preview) package 0.2.4

### Stack Trace

Uncaught TypeError: Invalid Point: (NaN, 0)

```
At /Applications/Atom Beta.app/Contents/Resources/app/node_modules/text-buffer/lib/point.js:63

TypeError: Invalid Point: (NaN, 0)
    at Function.module.exports.Point.assertValid (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/text-buffer/lib/point.js:63:21)
    at DisplayLayer.translateScreenPosition (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/text-buffer/lib/display-layer.js:333:17)
    at TextEditor.module.exports.TextEditor.bufferRowForScreenRow (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor.js:1108:38)
    at /packages/folded-code-preview/lib/folded-code-preview.js:69:35)
    at HTMLSpanElement.handle (/packages/folded-code-preview/node_modules/jquery/dist/jquery.js:5559:29)
    at HTMLBodyElement.dispatch (/packages/folded-code-preview/node_modules/jquery/dist/jquery.js:5206:27)
    at HTMLBodyElement.elemData.handle (/packages/folded-code-preview/node_modules/jquery/dist/jquery.js:5014:28)
```

### Commands

```
     -1:01.1.0 autocomplete-plus:cancel (input.hidden-input)
  4x -1:00.6.0 core:move-right (input.hidden-input)
     -0:59.7.0 editor:consolidate-selections (input.hidden-input)
     -0:59.1.0 editor:select-to-end-of-word (input.hidden-input)
     -0:57.1.0 core:backspace (input.hidden-input)
     -0:55.9.0 autocomplete-plus:cancel (input.hidden-input)
  7x -0:55.4.0 editor:move-to-end-of-word (input.hidden-input)
  6x -0:54 core:move-right (input.hidden-input)
     -0:50.6.0 autocomplete-plus:confirm (input.hidden-input)
  3x -0:50 editor:move-to-end-of-word (input.hidden-input)
  2x -0:49.2.0 core:move-left (input.hidden-input)
  2x -0:47.6.0 core:save (input.hidden-input)
  3x -0:29.3.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-loved-syntax.theme-one-dark-ui)
     -0:25.6.0 core:close (div.tool-panel.tree-view)
  2x -0:25.6.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-loved-syntax.theme-one-dark-ui)
     -0:17.4.0 core:copy (input.hidden-input)
```

### Non-Core Packages

```
aligner 1.2.3 
aligner-css 1.2.1 
aligner-javascript 1.2.0 
aligner-scss 1.3.1 
atom-beautify 0.30.3 
atom-focus-mode 0.11.0 
atom-no-tab-close-icon 1.0.0 
auto-update-packages 1.0.1 
autoclose-html 0.23.0 
autocomplete-paths 1.0.5 
better-window-title 1.0.3 
collapse-then-reveal 2.0.4 
colorio 0.2.1 
double-tag 0.9.0 
emmet 2.4.3 
fold-lines 0.2.2 
folded-code-preview 0.2.4 
fonts 3.0.2 
hey-pane 1.0.0 
hyperclick 0.1.2 
js-hyperclick 1.11.0 
jumpy 3.1.3 
keyboard-sounds 0.2.0 
language-vue 0.23.0 
loved-syntax 1.0.2 
magical-selection 2.0.3 
move-cursor-improved 0.1.0 
operator-mono 0.10.1 
pdf-view 0.59.0 
pigments 0.39.1 
seti-icons 1.5.4 
tab-numbers 0.6.0 
vue-hyperclick 0.2.0 
vue2-autocomplete 0.1.0-alpha.4 
vuejs2-snippets 0.9.0 
```

**Comment by Tecnology73** [comment]
How did you come by this error?

**Comment by rodrigoAbril** [comment]
Hello, the plugin its just not working at all, the error popped up when hovering over a collapsed div, could be that im using Atom beta...

**Comment by Tecnology73** [comment]
This should be fixed in the latest patch. Please re-open this issue if the problem persists :)
