### ISSUE TITLE
Uncaught TypeError: line.map is not a function

### ISSUE THREAD

**Issue by PotatoParser** [73CN0109y-Packages/folded-code-preview#9]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Microsoft Windows 10 Home
**Thrown From**: [folded-code-preview](https://github.com/73CN0109y-Packages/folded-code-preview) package 0.2.5

### Stack Trace

Uncaught TypeError: line.map is not a function

```
At C:\Users\MidSh\.atom\packages\folded-code-preview\lib\preview-block.js:270

TypeError: line.map is not a function
    at /packages/folded-code-preview/lib/preview-block.js:270:6
    at Array.forEach (<anonymous>)
    at PreviewBlock.wrapLines (/packages/folded-code-preview/lib/preview-block.js:268:9)
    at PreviewBlock.tokenizeBlock (/packages/folded-code-preview/lib/preview-block.js:131:31)
    at PreviewBlock.getCodeLines (/packages/folded-code-preview/lib/preview-block.js:115:15)
    at PreviewBlock.render (/packages/folded-code-preview/lib/preview-block.js:36:26)
    at Object.initialize (/packages/folded-code-preview/node_modules/etch/lib/component-helpers.js:32:31)
    at /packages/folded-code-preview/lib/preview-block.js:12:8)
    at Object.hoverFoldBlock (/packages/folded-code-preview/lib/folded-code-preview.js:97:36)
    at /packages/folded-code-preview/lib/folded-code-preview.js:63:47
```

### Commands

```
     -4:15.5.0 editor:fold-current-row (input.hidden-input)
     -4:07.2.0 core:undo (input.hidden-input)
  2x -4:01.5.0 core:close (input.hidden-input)
```

### Non-Core Packages

```
folded-code-preview 0.2.5 
sublime-ui-dark 0.0.7 
```

**Comment by rocketinventor** [comment]
Hi, this issue is still not fixed. I am on Atom `1.4.9`, using version `0.2.5`. I used to use this package heavily before it stopped working (a long time ago).

Steps:
- Enable plugin
- Fold text
- Hover over `...` (folded text icon)

I have not seen any public activity on Github from the project maintainer (@73CN0109y) in the last year. Maybe he doesn't exist anymore?

**Comment by PotatoParser** [comment]
Dang that’s really unfortunate ;-;
